In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('../Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [6]:
df = pd.get_dummies(df, columns=["home_ownership", "verification_status", "pymnt_plan","loan_status", "issue_d", "initial_list_status", "next_pymnt_d", "application_type", "hardship_flag", "debt_settlement_flag"])
df.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Jan-2019,issue_d_Mar-2019,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,0,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,0,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,0,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,0,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,0,1,0,1,0,1,1,0,1,1

# Split the Data into Training and Testing

In [7]:
# Create our features
X = df.drop(["loan_status_high_risk", "loan_status_low_risk"], axis=1)


# Create our target
y = df["loan_status_high_risk"]

In [8]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Jan-2019,issue_d_Mar-2019,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.451066,0.177238,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.497603,0.381873,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [9]:
# Check the balance of our target values
y.value_counts()

0    68470
1      347
Name: loan_status_high_risk, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [11]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
random_forest = BalancedRandomForestClassifier(n_estimators = 100)
random_forest = random_forest.fit(X_train, y_train)

In [12]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = random_forest.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7633646579110671

In [13]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[15275,  1829],
       [   37,    64]], dtype=int64)

In [14]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.89      0.63      0.94      0.75      0.58     17104
          1       0.03      0.63      0.89      0.06      0.75      0.55       101

avg / total       0.99      0.89      0.64      0.94      0.75      0.58     17205

In [15]:
# List the features sorted in descending order by feature importance
feature_names = X.columns
sorted(zip(random_forest.feature_importances_, feature_names), reverse=True)

[(0.06967054132180016, 'last_pymnt_amnt'),
 (0.06223126533752969, 'total_rec_prncp'),
 (0.060444136419927894, 'total_pymnt_inv'),
 (0.056402180041908195, 'total_rec_int'),
 (0.05044410365579827, 'total_pymnt'),
 (0.02800955636231326, 'int_rate'),
 (0.021394037067262547, 'issue_d_Jan-2019'),
 (0.01862993131937647, 'out_prncp'),
 (0.018069277776551113, 'mo_sin_old_rev_tl_op'),
 (0.018052057592161982, 'dti'),
 (0.016919520434893497, 'revol_bal'),
 (0.01642809118266978, 'installment'),
 (0.016195919660127633, 'mths_since_recent_inq'),
 (0.01610238213056732, 'annual_inc'),
 (0.01562494576057249, 'bc_util'),
 (0.015380358131582889, 'tot_hi_cred_lim'),
 (0.015262243652581126, 'il_util'),
 (0.014761182181838932, 'total_bal_il'),
 (0.014631777936407615, 'avg_cur_bal'),
 (0.014624416195355528, 'out_prncp_inv'),
 (0.014542450868038334, 'max_bal_bc'),
 (0.014539693223840027, 'tot_cur_bal'),
 (0.014387008248530612, 'mo_sin_old_il_acct'),
 (0.014331853643666079, 'total_bal_ex_mort'),
 (0.013535673254487306, 'bc_open_to_buy'),
 (0.013504075572708114, 'total_bc_limit'),
 (0.01312887746381173, 'issue_d_Mar-2019'),
 (0.013058581807065624, 'total_rev_hi_lim'),
 (0.012502790927185143, 'mths_since_rcnt_il'),
 (0.011925367755689533, 'total_il_high_credit_limit'),
 (0.011668475214294583, 'mths_since_recent_bc'),
 (0.01080436385066444, 'num_op_rev_tl'),
 (0.01079285601668565, 'loan_amnt'),
 (0.01077898541932362, 'num_rev_accts'),
 (0.01072112156821327, 'open_acc'),
 (0.0106395592255615, 'pct_tl_nvr_dlq'),
 (0.010437392853166918, 'total_acc'),
 (0.010276012994388522, 'all_util'),
 (0.010169675715719832, 'num_sats'),
 (0.009380865998719538, 'acc_open_past_24mths'),
 (0.00919794326072808, 'mo_sin_rcnt_tl'),
 (0.009107889846672528, 'num_il_tl'),
 (0.009047616583322322, 'inq_last_12m'),
 (0.008830900960981663, 'open_il_24m'),
 (0.008797251047864257, 'mo_sin_rcnt_rev_tl_op'),
 (0.008623871301725525, 'num_tl_op_past_12m'),
 (0.008250244253804299, 'total_cu_tl'),
 (0.008062068133990439, 'num_actv_rev_tl'),
 (0.007356802559464986, 'open_acc_6m'),
 (0.007304974494861402, 'open_rv_24m'),
 (0.0072784331852380505, 'num_rev_tl_bal_gt_0'),
 (0.007207993480031534, 'num_bc_tl'),
 (0.007100408193885328, 'num_actv_bc_tl'),
 (0.007065958306902214, 'inq_fi'),
 (0.00689045758122754, 'num_bc_sats'),
 (0.006399954935924528, 'open_act_il'),
 (0.0061540610311511534, 'total_rec_late_fee'),
 (0.005934883451606385, 'mort_acc'),
 (0.005261125464133789, 'open_rv_12m'),
 (0.0046190003941440185, 'inq_last_6mths'),
 (0.004498391441826616, 'issue_d_Feb-2019'),
 (0.004314702418450988, 'delinq_2yrs'),
 (0.004019537282976383, 'percent_bc_gt_75'),
 (0.0040045160031479225, 'open_il_12m'),
 (0.003913470108174237, 'next_pymnt_d_Apr-2019'),
 (0.003880878306678553, 'tot_coll_amt'),
 (0.0035419944377449086, 'next_pymnt_d_May-2019'),
 (0.0033862785619018674, 'num_accts_ever_120_pd'),
 (0.002415347408236208, 'application_type_Joint App'),
 (0.0023534398429683515, 'verification_status_Source Verified'),
 (0.002212877550402644, 'application_type_Individual'),
 (0.00213936836577458, 'pub_rec_bankruptcies'),
 (0.0014327046823109713, 'home_ownership_OWN'),
 (0.0013851801415309386, 'initial_list_status_f'),
 (0.0012014121529877902, 'home_ownership_RENT'),
 (0.0011747305822307028, 'verification_status_Verified'),
 (0.001167659544193115, 'verification_status_Not Verified'),
 (0.0011052948754198936, 'pub_rec'),
 (0.0008475431026157831, 'initial_list_status_w'),
 (0.0007649214866060438, 'num_tl_90g_dpd_24m'),
 (0.0007338383101227627, 'home_ownership_MORTGAGE'),
 (0.0005323571150035472, 'collections_12_mths_ex_med'),
 (7.811202804835696e-05, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'home_ownership_ANY'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [16]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators= 100, random_state=1)
eec = eec.fit(X_train, y_train)

In [18]:
# Calculated the balanced accuracy score
y_pred = eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9328586214561587

In [19]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[16162,   942],
       [    8,    93]], dtype=int64)

In [20]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.94      0.92      0.97      0.93      0.87     17104
          1       0.09      0.92      0.94      0.16      0.93      0.87       101

avg / total       0.99      0.94      0.92      0.97      0.93      0.87     17205